### ISSUE TITLE
Spring Cloud Config feature list

### ISSUE THREAD

**Issue by sophiaso** [microsoft/spring-cloud-azure#327]
Bug fix and pending features for the integration with priorities:

- [x] Next page request `Medium`  #398 

- [x] Add user agent `High` #328 

- [x] MSI credential support `High`   #351 #356

- [x] Poll/watch `Medium` #376 

- [x] Fail fast check `Medium`  #330 

- [ ] Configurable property source locator order `Medium`  #329 

- [x] ~~Configurable property name separator `Medium`~~ "/" or "." supported

- [ ] Retry when request fails `Low`

- [ ] Configurable request timeout `Low`

- [ ] Replace Apache HttpClient with RestTemplate?  `Low`

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
